name: push to Main
 
# Controls
on:
  workflow_dispatch:
 
#Jobs
jobs:
  pushjob:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
 
      - name: Changes to Feature Branches
        run: |
          git config --global user.email "karthikvarma2912@gmail.com"
          git config --global user.name "karthikvarma2912"
          echo "New Changes to feature branch" >> new.txt
          git add new.txt
          git commit -m "Add New Changes"
 
      - name: Push new changes
        env: 
          TOKEN: ${{secrets.PAT_WorkFlow}}
        run: |
          git push origin main
