name: push to Main
 
# Controls
on:
  workflow_dispatch:
 
#Jobs
jobs:
  pushjob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
 
      - name: Changes to Feature Branches
        run: |
          git config --global user.email "karthikvarma2912@gmail.com"
          git config --global user.name "karthikvarma2912"
          echo "New Changes to main branch" >> new.txt
          git add new.txt
          git commit -m "Add New Changes"
 
      - name: Push new changes
        env: 
          GITHUB_TOKEN: ${{secrets.PAT}}
        run: |
          git push origin main
