name: Comment on PR
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  commentjob:
    runs-on: ubuntu-latest
    steps:
      - name: comment on PR
        env: 
          GITHUB_TOKEN: ${{ secrets.secret1 }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
          -d '{"body": "Thank you for your contribution!"}' \https://api.github.com/repos/karthikvarma2912/pdc-devops/issues/$PR_NUMBER/comments
 
