name: CI
on:  
  push:
    branches: ['main']
  workflow_dispatch:
    inputs:
       username:
         description: 'A username should be passed'
         required: true
         type: string

jobs:
  printStatement:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
      - name: print the username
        run: echo the userName is ${{inputs.username}}
      - name: print the actor
        run: echo the actor is ${{ github.actor }}
    
